### PR TITLE
Update settings.py

### PR DESCRIPTION
**Pull request by sarcasticsamm**

### CODE REVIEW

**Comment by sarcasticsamm** [comment]
@app.on_callback_query(filters.regex("gib_source") & ~BANNED_USERS)
@languageCB
async def gib_repo(client, CallbackQuery, _):
    await CallbackQuery.edit_message_media(
        InputMediaVideo("https://te.legra.ph/file/3fcea5c53fd10c831470a.mp4"),
        reply_markup=InlineKeyboardMarkup(
            [[InlineKeyboardButton(text="ʙᴀᴄᴋ", callback_data=f"settingsback_helper")]]
        ),
    )

**Comment by sarcasticsamm** [comment]
@app.on_callback_query(filters.regex("gib_source") & ~BANNED_USERS)
@languageCB
async def gib_repo(client, CallbackQuery, _):
    await CallbackQuery.edit_message_media(
        InputMediaVideo("https://te.legra.ph/file/3fcea5c53fd10c831470a.mp4"),
        reply_markup=InlineKeyboardMarkup(
            [[InlineKeyboardButton(text="ʙᴀᴄᴋ", callback_data=f"settingsback_helper")]]
        ),
    )

**Comment by sarcasticsamm** [comment]
Jwh

**Comment by sarcasticsamm** [comment]
Gud

**Comment by sarcasticsamm** [comment]
**jwjhej**

**Comment by Rahulsharma45** [comment]
> @app.on_callback_query(filters.regex("gib_source") & ~BANNED_USERS) @languageCB async def gib_repo(client, CallbackQuery, _): await CallbackQuery.edit_message_media( InputMediaVideo("https://te.legra.ph/file/3fcea5c53fd10c831470a.mp4"), reply_markup=InlineKeyboardMarkup( [[InlineKeyboardButton(text="ʙᴀᴄᴋ", callback_data=f"settingsback_helper")]] ), )

Start.py bhi edit krle

**Pull request closed without merging**
