### PR TITLE
musicBot

### PR DESCRIPTION
**Pull request by ROSHANOPX**
HY GUYS WELCOME

### CODE REVIEW

**Comment by Devansh-Bots** [comment]
Gajab lode ho bc. Edit krke pull mar rhe

**Comment by Radhaxd** [comment]
Hehe

**Comment by AnonymousX1025** [comment]
> Hehe

Yaha bhi block karu ?

**Comment by Radhaxd** [comment]
Aur moti kesi ha

**Comment by Radhaxd** [comment]
Pranjal ho m

**Comment by Radhaxd** [comment]
ye kya chutiyapa hai bc

**Comment by AnonymousX1025** [comment]
> ye kya chutiyapa hai bc

Wanna see magic ?

**Comment by FabinoXD** [comment]
ok

**Comment by Devansh-Bots** [comment]
Black Megik krdiya kisi ne

**Comment by AnonymousX1025** [comment]
> Black Megik krdiya kisi ne

Haan ye karlo pehle

**Comment by Devansh-Bots** [comment]
> > Black Megik krdiya kisi ne
> 
> Haan ye karlo pehle

Jaldi waha se hato

**Pull request closed without merging**
